server:
  port: 9090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: beverage
          uri: lb://beverage-service
          predicates:
            - Path=/api/beverage/**

        - id: order
          uri: lb://order-service
          predicates:
            - Path=/api/order/**

  sleuth:
    reactor:
      instrumentation-type: decorate-on-each
  zipkin:
    base-url: http://localhost:9411

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
